-- 1. Table des citoyens (SIV)
CREATE TABLE IF NOT EXISTS public.citizens (
  id TEXT PRIMARY KEY,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  birthdate TEXT,
  gender TEXT,
  phone_number TEXT,
  nationality TEXT,
  height TEXT
);

-- 2. Table des véhicules (SIV)
CREATE TABLE IF NOT EXISTS public.vehicles (
  plate TEXT PRIMARY KEY,
  owner TEXT, -- This corresponds to citizen_id
  model TEXT,
  type TEXT,
  vehicle_hash BIGINT,
  state TEXT, -- 'Stored', 'Out', etc.
  color TEXT, -- Added color column
  FOREIGN KEY (owner) REFERENCES public.citizens(id)
);

-- 3. Table des avis de recherche
CREATE TABLE IF NOT EXISTS public.wanted (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  citizen_id TEXT,
  name TEXT, -- Fallback if citizen_id is null
  photo_url TEXT,
  reason TEXT NOT NULL,
  added_by BIGINT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'active', -- 'active', 'arrested'
  FOREIGN KEY (citizen_id) REFERENCES public.citizens(id),
  FOREIGN KEY (added_by) REFERENCES public.users(id)
);

-- 4. RLS Policies (Security)
ALTER TABLE public.citizens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wanted ENABLE ROW LEVEL SECURITY;

-- Allow all access (matching project's current permissive config)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'citizens' AND policyname = 'Enable all access for all users'
    ) THEN
        CREATE POLICY "Enable all access for all users" ON public.citizens FOR ALL USING (true) WITH CHECK (true);
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'vehicles' AND policyname = 'Enable all access for all users'
    ) THEN
        CREATE POLICY "Enable all access for all users" ON public.vehicles FOR ALL USING (true) WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'wanted' AND policyname = 'Enable all access for all users'
    ) THEN
        CREATE POLICY "Enable all access for all users" ON public.wanted FOR ALL USING (true) WITH CHECK (true);
    END IF;
END
$$;

-- FIX: Add missing color column to vehicles if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='vehicles' AND column_name='color') THEN
        ALTER TABLE public.vehicles ADD COLUMN color TEXT;
    END IF;
END $$;
