-- AJOUTEZ CETTE TABLE DANS SUPABASE POUR LE SYSTÈME DE CASIER JUDICIAIRE

-- Table des citoyens (casiers judiciaires)
CREATE TABLE public.citoyens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    date_naissance TEXT,
    telephone TEXT,
    adresse TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index pour recherche rapide par nom/prénom
CREATE INDEX idx_citoyens_nom ON public.citoyens(nom);
CREATE INDEX idx_citoyens_prenom ON public.citoyens(prenom);

-- Enable RLS
ALTER TABLE public.citoyens ENABLE ROW LEVEL SECURITY;

-- Policy permissive
CREATE POLICY "Enable all access for all users" ON public.citoyens FOR ALL USING (true) WITH CHECK (true);

-- Modifier la table rapports pour référencer les citoyens
ALTER TABLE public.rapports ADD COLUMN IF NOT EXISTS citoyen_id BIGINT REFERENCES public.citoyens(id);
