-- COPIEZ CE CODE DANS L'ÉDITEUR SQL DE SUPABASE

-- 1. Table des utilisateurs
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    nom TEXT NOT NULL,
    prenom TEXT NOT NULL,
    matricule TEXT UNIQUE NOT NULL,
    grade TEXT DEFAULT 'Gardien de la Paix',
    role TEXT DEFAULT 'agent',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table des amendes
CREATE TABLE public.amendes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    infraction TEXT NOT NULL,
    montant TEXT,
    recidive TEXT,
    retrait_points TEXT,
    prison TEXT,
    immobilisation TEXT,
    fourriere TEXT,
    categorie TEXT DEFAULT 'Autre'
);

-- 3. Table des rapports
CREATE TABLE public.rapports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id BIGINT REFERENCES public.users(id),
    citoyen_nom TEXT NOT NULL,
    citoyen_prenom TEXT NOT NULL,
    amende_id BIGINT REFERENCES public.amendes(id),
    montant_applique TEXT,
    description TEXT,
    lieu TEXT,
    est_recidive BOOLEAN DEFAULT FALSE,
    date_creation TIMESTAMPTZ DEFAULT NOW(),
    statut TEXT DEFAULT 'En cours'
);

-- 4. Table des logs (NOUVEAU)
CREATE TABLE public.logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    action TEXT NOT NULL,
    details TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Désactiver RLS (Row Level Security) pour faciliter l'accès depuis le backend
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amendes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rapports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;

-- Créer des polices permissives pour permettre l'accès public
CREATE POLICY "Enable all access for all users" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.amendes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.rapports FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Enable all access for all users" ON public.logs FOR ALL USING (true) WITH CHECK (true);
